title: addadi
description: Adventures in Overengineering
url: "https://addadi.github.io"
timezone: Asia/Jerusalem
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "air"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
