title: addadi
description: Adventures in Overengineering
url: "https://addadi.github.io"
timezone: Asia/Jerusalem
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      author_profile: true
