theme: minima
title: addadi
description: Adventures in Overengineering
url: "https://addadi.github.io"
timezone: Asia/Jerusalem
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
